"""Docker Compose file generation."""

from typing import List

from .base import FileGenerator, GenerationContext


class ComposeGenerator(FileGenerator):
    """Generates .opencode/docker-compose.yaml for runtime."""
    
    def generate(self, ctx: GenerationContext) -> None:
        """Generate static docker-compose.yaml template.
        
        The template uses environment variable interpolation:
        - OCF_IMAGE_ID: Set at launch time after build
        - PWD: Set at launch time to repo root
        - Other vars: Loaded from .opencode/.env
        """
        compose_path = ctx.opencode_dir / "docker-compose.yaml"
        compose_content = self._generate_template(ctx)
        compose_path.write_text(compose_content)
    
    def _generate_template(self, ctx: GenerationContext) -> str:
        """Generate compose file content as string."""
        lines = [
            "# Docker Compose file for OpenCode runtime",
            "# Generated by ocframework init",
            "",
            "services:",
            "  opencode:",
            '    image: "${OCF_IMAGE_ID}"',
            "    working_dir: /workspace",
            "    tty: true",
            "    stdin_open: true",
            "    environment:",
        ]
        
        env_vars = self._get_environment_variables()
        for var, default in env_vars:
            if default:
                lines.append(f"      - {var}=${{{var}:-{default}}}")
            else:
                lines.append(f"      - {var}=${{{var}:-}}")
        
        lines.append("    volumes:")
        volumes = self._get_volumes()
        for volume in volumes:
            lines.append(f"      - {volume}")
        
        lines.append("    command: opencode --continue")
        
        return "\n".join(lines) + "\n"
    
    def _get_environment_variables(self) -> List[tuple]:
        """Return list of (env_var_name, default_value) tuples."""
        return [
            ("OPENCODE_CONFIG", ""),
            ("XDG_CONFIG_HOME", "/root/.config"),
            ("XDG_DATA_HOME", "/root/.local/share"),
            ("XDG_STATE_HOME", "/root/.local/state"),
            ("XDG_CACHE_HOME", "/root/.cache"),
            ("OCF_MAIN_MODEL", ""),
            ("OCF_BUILD_MODEL", ""),
            ("OCF_SMALL_MODEL", ""),
            ("EDITOR", ""),
        ]
    
    def _get_volumes(self) -> List[str]:
        """Return list of volume mount strings with defaults for optional paths."""
        return [
            "${PWD}:/workspace",
            "${PWD}/.opencode/runtime_data/.cache:${XDG_CACHE_HOME:-/root/.cache}",
            "${PWD}/.opencode/runtime_data/.local/share:${XDG_DATA_HOME:-/root/.local/share}",
            "${PWD}/.opencode/runtime_data/.local/state:${XDG_STATE_HOME:-/root/.local/state}",
            "${OCF_LOCAL_GLOBAL_AUTH_PATH:-/dev/null}:${XDG_DATA_HOME:-/root/.local/share}/opencode/auth.json:ro",
            "${OCF_LOCAL_FRAMEWORK_PATH:-/dev/null}/framework-config/config.json:${OCF_REMOTE_FRAMEWORK_CONFIG_PATH:-/tmp/unused}:ro",
            "${OCF_LOCAL_GLOBAL_CONFIG_PATH:-/dev/null}:${XDG_CONFIG_HOME:-/root/.config}/opencode:ro",
        ]
